export const chairMansMEssage = `
"Marking over five decades since our humble inception in 1974, it is with great pleasure that I, as Chairperson of the Meezan Group of Companies, reflect on our remarkable journey. This message of felicitation and greetings come with a deep sense of pride as my brother Ziaudeen Meezan and I, Ihithisham Meezan recall the many milestones we have overcome, guided by an unwavering "Never Say Never" spirit.
Looking back, vivid childhood memories of visiting sprawling tea plantations with my elder siblings still resonate deeply. Even then, the sheer scale and grandeur captivated me, instilling a certainty that this would one day be my calling. That intuition proved correct. Zia and I embarked on our planting endeavors in our late teens, a career path that has presented its share of setbacks and disappointments. However, by the grace of Allah, we have consistently navigated both prosperous and challenging times.
The expropriation of our land by the Land Reform Commission (LRC) in the late seventies was a deeply distressing period. We feared it represented an irreversible loss. Yet, recognizing the injustice, we resolved to fight for what was rightfully ours. What followed was an arduous twelve-year legal battle against the LRC, a contest where both sides exerted their full efforts. Our perseverance ultimately led to the successful acquisition of the Nagalla plantation in 1986. Subsequently, in 1990, the Ancoombra plantation was reclaimed, and finally, in 2002, the Hatale tea plantation was returned to us as part of the compensation for what had been taken. Furthermore, our ownership expanded with the strategic purchase of the Dartry Tea Factory in 2009. In retrospect, the struggle was indeed worthwhile.
Today, with nearly 35 years of dedicated experience, a committed permanent workforce of approximately 150 individuals, and an annual black tea production nearing two million kilograms, our commitment remains steadfast: to provide our valued customers and discerning connoisseurs with the same uncompromising quality that defined us 25 years ago – superior, garden-fresh, handpicked, meticulously perfected, and packed unblended teas. Our enduring pursuit of perfection has been matched only by the unwavering commitment, resolute perseverance, and unwavering integrity we have invested in all our endeavors. As I often remind our team, “With sufficient effort, the seemingly impossible becomes possible!”
At Meezans, we hold a sincere aspiration for the continued prosperity of the Sri Lankan Tea Industry and aim to inspire all tea growers nationwide to prioritize the highest quality production, thereby securing a competitive advantage in the global marketplace.
Our vision is to establish ‘Meezan Plantations’ as a benchmark of excellence in the region, and we have proactively implemented various measures to maximize yields in pursuit of this objective. Our plantations in Hatale and Ancoombra currently achieve a yield of 2500 kilograms per hectare. However, our long-term ambition is to elevate this to the range of 4000 kilograms per hectare and beyond.
I am pleased to announce the successful integration of the CTC (Cut, Twist, and Curl) method alongside the fully automated orthodox manufacturing process at our state-of-the-art factory in Ancoombra. I am also proud to highlight that the Ancoombra Tea factory is among the pioneering facilities in the region to operate both these advanced manufacturing techniques under one roof.
"

`